# Generated by Django 5.0.3 on 2025-03-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
